### ISSUE TITLE
invalid perfdata value (icinga2 with influxdb)

### ISSUE THREAD

**Issue by luca-rhk** [NETWAYS/check_liebert_mpx#1]
Hello,

icinga2 doesn't seem to like the performance data that is produced by this script. The issue seems to be caused by the following two lines:
https://github.com/NETWAYS/check_liebert_mpx/blob/master/check_liebert_mpx.pl#L289
https://github.com/NETWAYS/check_liebert_mpx/blob/master/check_liebert_mpx.pl#L360

If I remove the `A` from the lines `"%.2fA;%.1f:%.1f;%.1f:%.1f;%.1f;%.1f",`, icinga2 starts to like the output and writes the data to InfluxDB. Otherwise icinga2 simply states: `Ignoring invalid perfdata value`
Is there the possibility to either add parameters to influence the syntax of the output perfdata or to remove the `A` from the string?
Or is there something that I am missing here to convince icinga2 to like the output?

Some general info about InfluxDB and icinga2 (although I do not think that it is necessary in this case):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 83e7f59f33f0
 ```

```
InfluxDB shell version: 1.6.1
```

**Comment by martialblog** [comment]
Should work with Icinga2 2.13 an higher https://github.com/Icinga/icinga2/pull/7871
